# sklearn的学习

In [2]:
from sklearn.datasets import load_iris

## sklearn数据  
数据分类：  
* 训练集（75%）：用于建立模型  
* 测试集（25%）：用来测试模型  

加载获取的数据API：
* datasets.load_*():获取小规模数据集，数据包含在datasets里  
* datasets.fetch_*(data_home=None)：获取大规模数据集，需要从网络上下载，函数的第一个参数是data_home，表示数据集下载的目录,默认是 ~/scikit_learn_data/  

获取数据集返回的类型  
* load和fetch*返回的数据类型datasets.base.Bunch(字典格式)  
--data：特征数据数组,是(n_samples,n_features)的二维numpy.ndarray 数组  
--target：标签数组,是n_samples 的一维 numpy.ndarray 数组  
--DESCR：数据描述  
--feature_names：特征名,新闻数据，手写数字、回归数据集没有  
--target_names：标签名,回归数据集没有



In [3]:
li=load_iris()
print('获取特征值')
print(li.data)
print('目标值')
print(li.target)

获取特征值
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 

In [4]:
print(li.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
print(li.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(li.target_names)

['setosa' 'versicolor' 'virginica']


## 数据集划分  
### sklearn.model_selection.train_test_split(*arrays, **options)  
* x：数据集的特征值  
* y：数据集的标签值  
* test_size：测试集的大小，一般为float  
* random_state：随机数种子,不同的种子会造成不同的随机采样结果。相同的种子采样结果相同。  
* return：训练集特征值，测试集特征值，训练标签，测试标签(默认随机取)	

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
li=load_iris()
x_train,x_test,y_train,y_test=train_test_split(li.data,li.target,test_size=0.25)

In [10]:
print('训练集特征值和目标值:',x_train,y_train)

训练集特征值和目标值: [[6.3 2.9 5.6 1.8]
 [5.4 3.  4.5 1.5]
 [6.7 2.5 5.8 1.8]
 [5.7 2.6 3.5 1. ]
 [5.  3.  1.6 0.2]
 [6.2 2.2 4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.6 3.2 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.5 0.3]
 [4.7 3.2 1.3 0.2]
 [7.7 2.8 6.7 2. ]
 [5.4 3.9 1.3 0.4]
 [6.6 2.9 4.6 1.3]
 [7.4 2.8 6.1 1.9]
 [6.4 2.8 5.6 2.2]
 [6.3 2.5 4.9 1.5]
 [5.6 2.8 4.9 2. ]
 [5.  3.3 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [6.1 2.9 4.7 1.4]
 [6.8 3.  5.5 2.1]
 [6.2 3.4 5.4 2.3]
 [6.7 3.  5.  1.7]
 [4.4 2.9 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [6.5 3.  5.5 1.8]
 [5.6 3.  4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [5.  3.6 1.4 0.2]
 [6.1 2.6 5.6 1.4]
 [4.9 3.  1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [6.3 2.5 5.  1.9]
 [6.3 2.8 5.1 1.5]
 [6.3 3.3 4.7 1.6]
 [4.4 3.2 1.3 0.2]
 [5.6 2.5 3.9 1.1]
 [5.7 2.9 4.2 1.3]
 [7.  3.2 4.7 1.4]
 [6.9 3.1 4.9 1.5]
 [5.5 3.5 1.3 0.2]
 [5.5 2.4 3.7 1. ]
 [5.1 3.4 1.5 0.2]
 [6.8 3.2 5.9 2.3]
 [5.8 2.7 3.9 1.2]
 [7.9 3.8 6.4 2. ]
 [4.9 3.1 1.5 0.1]
 [6.  2.2 5.  1.5]
 [7.3 2.9 6.3 1.8]
 [6.  3.4 4.5 1.6]


In [11]:
print('测试集的特征值和目标值：',x_test,y_test)

测试集的特征值和目标值： [[4.6 3.4 1.4 0.3]
 [4.9 2.5 4.5 1.7]
 [5.6 3.  4.1 1.3]
 [6.4 3.1 5.5 1.8]
 [5.  3.4 1.6 0.4]
 [6.5 3.  5.8 2.2]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  4.2 1.5]
 [5.5 4.2 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.7 0.2]
 [7.1 3.  5.9 2.1]
 [5.5 2.3 4.  1.3]
 [6.4 3.2 4.5 1.5]
 [5.1 2.5 3.  1.1]
 [5.1 3.5 1.4 0.3]
 [5.7 4.4 1.5 0.4]
 [6.3 2.7 4.9 1.8]
 [4.4 3.  1.3 0.2]
 [5.  3.2 1.2 0.2]
 [5.8 4.  1.2 0.2]
 [6.7 3.1 5.6 2.4]
 [6.5 2.8 4.6 1.5]
 [6.1 3.  4.6 1.4]
 [5.4 3.9 1.7 0.4]
 [5.6 2.7 4.2 1.3]
 [6.  2.9 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.9 0.4]
 [5.5 2.5 4.  1.3]
 [6.5 3.  5.2 2. ]
 [5.9 3.  5.1 1.8]
 [6.9 3.1 5.4 2.1]
 [6.6 3.  4.4 1.4]
 [6.3 3.3 6.  2.5]
 [6.7 3.3 5.7 2.1]
 [6.4 2.9 4.3 1.3]] [0 2 1 2 0 2 0 1 0 0 0 2 1 1 1 0 0 2 0 0 0 2 1 1 0 1 1 1 1 0 1 2 2 2 1 2 2
 1]


## 用于分类的大数据集  
sklearn.datasets.fetch_20newsgroups(data_home=None,subset=‘train’)
* subset: 'train'或者'test','all'，可选，选择要加载的数据集.
训练集的“训练”，测试集的“测试”，两者的“全部”  

datasets.clear_data_home(data_home=None)  
* 清除目录下的数据

In [12]:
from sklearn.datasets import fetch_20newsgroups

In [16]:
news=fetch_20newsgroups(subset='all')

In [14]:
print(news.data)

ellington is still on Broadway and Canal, but they\'re\nnot cheap, and not surplus.  It\'s mostly a TV repairman\'s store.\n\n-- Jeffrey Jonas\njeffj@panix.com\n-- \nJeffrey Jonas\n\njeffj@panix.com\n', 'From: jake@bony1.bony.com (Jake Livni)\nSubject: Re: Israel\'s Expansion II\nOrganization: The Department of Redundancy Department\nLines: 63\n\nIn article <1993Apr27.023914.9453@Virginia.EDU> ab4z@Virginia.EDU ("Andi Beyer") writes:\n>jake@bony1.bony.com  writes:\n>> In article <1993Apr25.222120.3411@Virginia.EDU> ab4z@Virginia.EDU ("Andi Beyer") writes:\n>> >waldo@cybernet.cse.fau.edu  writes:\n>> \n>> >> ALL Jews suffered during WWII, not just our beloved who perished or were \n>> >> tortured.  We ALL suffered.  \n>> \n>> >\tAll humans suffered emotionally, some Jews and many\n>> >others suffered physically. \n>> \n>> I\'m just waiting for Andi to tell us that African Americans should\n>> start paying compensation to White Americans who "suffered" from being \n>> slave owners.\n\n>\

In [15]:
print(news.target)

[10  3 17 ...  3  1  7]


## sklean回归数据集

In [18]:
from sklearn.datasets import load_boston

In [19]:
lb=load_boston()

In [20]:
# 获取特征值
print(lb.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [21]:
# 目标值
print(lb.target)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [22]:
print(lb.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

## 转换器  
fit_transform():输入数据直接转换  
fit():输入数据，不转换（计算平均值，方差）  
transform():进行数据的转换

## 估计器（estimator）
1、用于分类的估计器：  
* sklearn.neighbors	k-近邻算法  
* sklearn.naive_bayes      贝叶斯  
* sklearn.linear_model.LogisticRegression     逻辑回归  

2、用于回归的估计器：  
* sklearn.linear_model.LinearRegression     线性回归  
* sklearn.linear_model.Ridge      岭回归 

