# sklearn学习

In [19]:
# 导入包
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import jieba

In [2]:
con1=jieba.cut('今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。')

con2=jieba.cut('我们看到的从很远星系来的光是在几百万年之前发出的，这样当我们看到宇宙时，我们是在看它的过去。')

con3=jieba.cut('如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。')

print(con1)
print(con2)
print(con3)

<generator object Tokenizer.cut at 0x000001B514EA2DD0>
<generator object Tokenizer.cut at 0x000001B514EA2C10>
<generator object Tokenizer.cut at 0x000001B514EA2D60>


In [3]:
#转换为列表
content1=list(con1)
content2=list(con2)
content3=list(con3)

#把列表转化为字符串
c1=' '.join(content1)
c2=' '.join(content2)
c3=' '.join(content3)

print(c1)
print('*'*100)
print(c2)
print('*'*100)
print(c3)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\17575\AppData\Local\Temp\jieba.cache
Loading model cost 0.585 seconds.
Prefix dict has been built successfully.
今天 很 残酷 ， 明天 更 残酷 ， 后天 很 美好 ， 但 绝对 大部分 是 死 在 明天 晚上 ， 所以 每个 人 不要 放弃 今天 。
****************************************************************************************************
我们 看到 的 从 很 远 星系 来 的 光是在 几百万年 之前 发出 的 ， 这样 当 我们 看到 宇宙 时 ， 我们 是 在 看 它 的 过去 。
****************************************************************************************************
如果 只用 一种 方式 了解 某样 事物 ， 你 就 不会 真正 了解 它 。 了解 事物 真正 含义 的 秘密 取决于 如何 将 其 与 我们 所 了解 的 事物 相 联系 。


## 归一化处理
* 使得一个特征对最终结果不会造成巨影响

In [5]:
mm=MinMaxScaler()
data=mm.fit_transform([[90,2,10,40],[60,4,15,45],[75,3,13,46]])
print(data)

[[1.         0.         0.         0.        ]
 [0.         1.         1.         0.83333333]
 [0.5        0.5        0.6        1.        ]]


In [7]:
# 指定范围
mm=MinMaxScaler(feature_range=(2,3))
data=mm.fit_transform([[90,2,10,40],[60,4,15,45],[75,3,13,46]])
print(data)

[[3.         2.         2.         2.        ]
 [2.         3.         3.         2.83333333]
 [2.5        2.5        2.6        3.        ]]


## 标准化处理
通过对原始数据进行变换把数据变换到均值为0,标准差为1范围内  
标准化特点：<font color=pink>在已有样本足够多的情况下比较稳定，适合现代嘈杂大数据场景。</font>

归一化 | 标准化
:-|:- 
如果出现异常点，影响了最大值和最小值，那么结果显然会发生改变 | 如果出现异常点，由于具有一定数据量，少量的异常点对于平均值的影响并不大，从而方差改变较小

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
# 标准化缩放
std=StandardScaler()
data=std.fit_transform([[ 1., -1., 3.],[ 2., 4., 2.],[ 4., 6., -1.]])
print(data)

[[-1.06904497 -1.35873244  0.98058068]
 [-0.26726124  0.33968311  0.39223227]
 [ 1.33630621  1.01904933 -1.37281295]]


sklean中缺失值的处理--Imputer

In [37]:
# 导入Imputer,最新版本改动
from sklearn.impute import SimpleImputer
import numpy as np

In [44]:
im=SimpleImputer(missing_values=np.nan,strategy='mean',)
data=[[1,2],[np.nan,3],[7,6]]
im=im.fit_transform(data)
print(im)

[[1. 2.]
 [4. 3.]
 [7. 6.]]


## 降维  
定义：去除不必要的特征  

方法:  
* 特征选择  
* 主成分分析  

特征选择主要方法  
* Filter(过滤式):VarianceThreshold--(本文主要讲解)  
* Embedded(嵌入式)：正则化、决策树  
* Wrapper(包裹式)

In [1]:
# 导入包
from sklearn.feature_selection import VarianceThreshold

In [7]:
# 方差特征选择--删除低放出特征
var=VarianceThreshold(threshold=1.0)
data=var.fit_transform([[0, 2, 0, 3],[0, 1, 4, 3],[0, 1, 1, 3]])
# print('原始值:',[[0, 2, 0, 3],[0, 1, 4, 3],[0, 1, 1, 3]])
print(data)

[[0]
 [4]
 [1]]


主成分分析  
- PCA：特征数量达到上百时候，考虑数据的简化  
-- 主要参数:PCA(n_components=None):将数据分解为较低维数空间  
---------- n_components:90%-100%,通常使用90%-95%（经验）


In [9]:
# 导入包
from sklearn.decomposition import PCA

In [10]:
pca=PCA(n_components=0.9)
data=pca.fit_transform([[2,8,4,5],[6,3,0,8],[5,4,9,1]])
print(data)

[[ 1.28620952e-15  3.82970843e+00]
 [ 5.74456265e+00 -1.91485422e+00]
 [-5.74456265e+00 -1.91485422e+00]]


主成分分析案例  

案例目的：把用户分成几个类别

数据:  
products.csv:商品信息  
order_products__prior.csv:订单与商品信息  
orders.csv:用户的订单信息  
aisles.csv:商品所属具体物品类别  

处理步骤：  
1、合并成一张表  
2、建立一个行、列数据---交叉表：特殊的分组表  
3、进行主成分分析

In [1]:
import pandas as pd
from sklearn.decomposition import PCA

In [2]:
# 读取四张表数据
prior=pd.read_csv(r'C:\Users\17575\VSCode\机器学习\Data\order_products__prior.csv')
aisles=pd.read_csv(r'C:\Users\17575\VSCode\机器学习\Data\aisles.csv')
products=pd.read_csv(r'C:\Users\17575\VSCode\机器学习\Data\products.csv')
orders=pd.read_csv(r'C:\Users\17575\VSCode\机器学习\Data\orders.csv')

In [3]:
# 将csv文件转化为DateFrame
prior=pd.DataFrame(prior)
aisles=pd.DataFrame(aisles)
products=pd.DataFrame(products)
orders=pd.DataFrame(orders)
# 标签改成一致
# aisles.columns=['aisle_id_x','aisle']

In [5]:
prior.head(3)

order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0

In [6]:
orders.head(3)

order_id  user_id eval_set  order_number  order_dow  order_hour_of_day  \
0   2539329        1    prior             1          2                  8   
1   2398795        1    prior             2          3                  7   
2    473747        1    prior             3          3                 12   

   days_since_prior_order  
0                     NaN  
1                    15.0  
2                    21.0

In [7]:
aisles.head(3)

aisle_id_x                  aisle
0           1  prepared soups salads
1           2      specialty cheeses
2           3    energy granola bars

In [8]:
products.head(3)

product_id                          product_name  aisle_id  department_id
0           1            Chocolate Sandwich Cookies        61             19
1           2                      All-Seasons Salt       104             13
2           3  Robust Golden Unsweetened Oolong Tea        94              7

In [4]:
# 合并一张表到一张表
_mg=pd.merge(prior,products,on=['product_id','product_id'])
_mg=pd.merge(_mg,orders,on=['order_id','order_id'])
mt=pd.merge(_mg,aisles,on=['aisle_id','aisle_id'])

In [5]:
mt.head(3)

order_id  product_id  add_to_cart_order  reordered        product_name  \
0         2       33120                  1          1  Organic Egg Whites   
1        26       33120                  5          0  Organic Egg Whites   
2       120       33120                 13          0  Organic Egg Whites   

   aisle_id  department_id  user_id eval_set  order_number  order_dow  \
0        86             16   202279    prior             3          5   
1        86             16   153404    prior             2          0   
2        86             16    23750    prior            11          6   

   order_hour_of_day  days_since_prior_order aisle  
0                  9                     8.0  eggs  
1                 16                     7.0  eggs  
2                  8                    10.0  eggs

In [6]:
# 建立行、列数据--交叉表
cross=pd.crosstab(mt['user_id'],mt['aisle'])

In [7]:
cross.head(5)

aisle    air fresheners candles  asian foods  baby accessories  \
user_id                                                          
1                             0            0                 0   
2                             0            3                 0   
3                             0            0                 0   
4                             0            0                 0   
5                             0            2                 0   

aisle    baby bath body care  baby food formula  bakery desserts  \
user_id                                                            
1                          0                  0                0   
2                          0                  0                0   
3                          0                  0                0   
4                          0                  0                0   
5                          0                  0                0   

aisle    baking ingredients  baking supplies decor  beauty  beers coolers  \
user_id                                                                     
1                         0                      0       0              0   
2                         2                      0       0              0   
3                         0                      0       0              0   
4                         0                      0       0              0   
5                         0                      0       0              0   

aisle    ...  spreads  tea  tofu meat alternatives  tortillas flat bread  \
user_id  ...                                                               
1        ...        1    0                       0                     0   
2        ...        3    1                       1                     0   
3        ...        4    1                       0                     0   
4        ...        0    0                       0                     1   
5        ...        0    0                       0                     0   

aisle    trail mix snack mix  trash bags liners  vitamins supplements  \
user_id                                                                 
1                          0                  0                     0   
2                          0                  0                     0   
3                          0                  0                     0   
4                          0                  0                     0   
5                          0                  0                     0   

aisle    water seltzer sparkling water  white wines  yogurt  
user_id                                                      
1                                    0            0       1  
2                                    2            0      42  
3                                    2            0       0  
4                                    1            0       0  
5                                    0            0       3  

[5 rows x 134 columns]

In [8]:
# 进行主成分分析
pca=PCA(n_components=0.9)

In [9]:
data=pca.fit_transform(cross)

In [10]:
print(data)

[[-2.42156587e+01  2.42942720e+00 -2.46636975e+00 ...  6.86800336e-01
   1.69439402e+00 -2.34323022e+00]
 [ 6.46320806e+00  3.67511165e+01  8.38255336e+00 ...  4.12121252e+00
   2.44689740e+00 -4.28348478e+00]
 [-7.99030162e+00  2.40438257e+00 -1.10300641e+01 ...  1.77534453e+00
  -4.44194030e-01  7.86665571e-01]
 ...
 [ 8.61143331e+00  7.70129866e+00  7.95240226e+00 ... -2.74252456e+00
   1.07112531e+00 -6.31925661e-02]
 [ 8.40862199e+01  2.04187340e+01  8.05410372e+00 ...  7.27554259e-01
   3.51339470e+00 -1.79079914e+01]
 [-1.39534562e+01  6.64621821e+00 -5.23030367e+00 ...  8.25329076e-01
   1.38230701e+00 -2.41942061e+00]]


In [11]:
data.shape

(206209, 27)